apiVersion: v1
kind: Service
metadata:
  name: {{ template "robustName" .Release.Name  }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "staticSite.labels" . | nindent 4 }}
  {{- if or .Values.gitRepository .Values.gitSha }}
  annotations:
    {{- if .Values.gitRepository }}
    gimlet.io/git-repository: {{ .Values.gitRepository }}
    {{- end }}
    {{- if .Values.gitSha }}
    gimlet.io/git-sha: {{ .Values.gitSha }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "staticSite.selectorLabels" . | nindent 4 }}
