replicaCount: 1
image:
  repository: zengxs/gitlab
  tag: "17-ce"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: gitlab.pangarabbit.com

namespace: infrastructure

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
