apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitlab-arm64-pangarabbit
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: gitlab-arm64-pangarabbit
  chart:
    spec:
      chart: gitlab-arm64-pangarabbit
      version: 0.1.9
      sourceRef:
        kind: HelmRepository
        name: gitlab-arm64-pangarabbit
      interval: 10m
  values:
    image:
      repository: zengxs/gitlab
      tag: "17.0"
      pullPolicy: IfNotPresent

    ingress:
      host: gitlab.pangarabbit.com
      ingressClassName: traefik
      tlsEnabled: true
      # annotations:
      #   cert-manager.io/cluster-issuer: letsencrypt-staging
      # nginxBasicAuth:
      #   user: admin
      #   password: secret

    # vars:
    #   MY_VAR: "value"

    replicas: 1

    nameOverride: ""
    fullnameOverride: ""

    podAnnotations: {}

    podLabels: {}

    podSecurityContext:
      fsGroup: 999

    securityContext: {}

    containerPort: 80

    resources:
      requests:
        cpu: "200m"
        memory: "200Mi"
      limits:
        cpu: "200m"
        memory: "200Mi"

    nodeSelector: {}

    tolerations: []

    probe:
      enabled: false
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    # Before you use a liveness probe: https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html
    livenessProbe:
      enabled: false
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    secretEnabled: false

    shell: "/bin/sh"

    podDisruptionBudgetEnabled: true
    spreadAcrossNodes: false

    nodePortEnabled: false

    # Set true to enable service monitor.
    monitor:
      enabled: false

    container: {}
    podSpec: {}
